# Meta Data for SEO

## Homepage
title = "AMMs For Prediction Markets"
titleSeparator = "-"
titleAddition = "Just Win"
description = "Description."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = ""
twitterCreator = ""
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = ""
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by the Just Win team. Funded by Gnosis."

# Alert
alert = false
alertText = "You Just Win"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
